### ISSUE TITLE
perfview System.FormatException when viewing CPU stacks section in perfview collected from Kubernetes POD

### ISSUE THREAD

**Issue by paraspatidar** [dotnet/corefx-tools#95]
Hi,
I am running dotnet core (2.2.2) process on K8 pod with elevated rights and could do a perf collect without any issue and trace is created as well as CPU stack (perf.data.txt) is created.

However , when coping to windows and opening the CPU stack , it fails with exception : 

`
System.FormatException: Input string was not in a correct format
`

this happens when we do 
`sudo ./perfcollect collect sample'  

however if we pass on the process id (-pid param) , then CPU traces doesnt gather at all  as mentioned in another issue  : 
https://github.com/dotnet/corefx-tools/issues/84
&

https://github.com/dotnet/coreclr/issues/18452

this format issue was said to be fixed in https://github.com/Microsoft/perfview/issues/166
but i am using perfview 2.0.26 and facing this issue.
here is sample trace  : 
https://drive.google.com/file/d/1eyQWCIAefVyCCp0zm5vCSr0f0Jp99EGC/view?usp=sharing

**Comment by sywhang** [comment]
cc @vancem 

Vance, should we move this to the PerfView repo?

**Comment by vancem** [comment]
Yes, go head and do that.

**Comment by vancem** [comment]
This is being fixed by https://github.com/Microsoft/perfview/pull/890

**Comment by vancem** [comment]
I am closing this as the fix has been checked into the PerfView repo.   Note that a release with that fix has not yet happened (but you can build PerfView yourself if desired).
