### ISSUE TITLE
Syntax error in perfcollect

### ISSUE THREAD

**Issue by rantrave-git** [dotnet/corefx-tools#97]
After the last update https://github.com/dotnet/corefx-tools/blob/master/src/performance/perfcollect/perfcollect contains syntax error at line 1275.
```sh
./perfcollect: line 1276: syntax error near unexpected token `then'
./perfcollect: line 1276: `    then'
```

`elseif` should be `elif`

**Comment by sywhang** [comment]
Should be fixed with #98. Thanks for bringing this up!
